5lab_django_intro/my_site/loginApp/urls.py
from django.urls import path
# from .views import MyLoginView
from django.contrib.auth.views import LogoutView 
from . import views

app_name = "loginApp"
urlpatterns = [
    path("", views.home_view, name="home"),
    path('login/', views.loginview, name='login'),
    path("afterLogin/", views.afterLogin, name="afterLogin"),
    path('logout/', views.logout_view ,name='logout'),
]

5lab_django_intro/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from loginApp import views as login_views
urlpatterns = [
    path("", login_views.home_view, name="home"),
    path("obrazkiApp/", include("obrazkiApp.urls")),
    path("loginApp/", include("loginApp.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

5lab_django_intro/my_site/obrazkiApp/urls.py
from django.urls import path
# from .views import MyLoginView
from django.contrib.auth.views import LogoutView 
from . import views

app_name = "obrazkiApp"
urlpatterns = [
    path("", views.index, name="index"),
    path("svg_form/", views.svg_form_view, name="svg_img_form"),
    path("<int:svg_id>/", views.svg_detail, name="svg_detail"),
    path("svg_list/", views.list_svg_images, name="svg_list"),
    path("svg_modifiable_list/", views.svg_modifiable_list, name="svg_modifiable_list"),
    path("<int:svg_id>/modifiable/", views.svg_modifiable_detail, name="svg_modifiable_detail"),
    path("<int:svg_id>/<int:rect_id>/", views.svg_remove_rect, name="svg_remove_rect"),
]

5lab_django_intro/my_site/loginApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def home_view(request):
    return render(request, 'loginApp/home.html')

@login_required
def afterLogin(request):
    return render(request, 'loginApp/afterLogin.html')

def loginview(request):
    if request.user.is_authenticated:
        return redirect('loginApp:afterLogin')
    
    if request.method == 'POST':
        user = authenticate(request, username=request.POST["username"],
                            password=request.POST["password"])
        if user is not None:
            login(request, user)
            messages.success(request, 'Logged in successfully')
            return redirect('loginApp:afterLogin')
        else:
            messages.error(request, 'Logged in Fail')
    return render(request, 'loginApp/login.html')

def logout_view(request):
    logout(request)
    return redirect('loginApp:login')

5lab_django_intro/my_site/loginApp/templates/loginApp/afterLogin.html
<head>
    <title>Welcome to LOGIN SITE</title>
</head>
{% extends 'loginApp/base.html' %} 

{% block content %}
<div class="p-2 m-1">

    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    <p>Thank you for visiting ArtUser.</p>
    <br>
    <a href="{% url 'obrazkiApp:index' %}">
        <button class="btn btn-success font-weight-bold">
            Go to obrazkiApp index
        </button>
    </a>
    <br>
    <a href="{% url 'loginApp:logout' %}">
        <button class="btn btn-danger font-weight-bold">
            Logout
        </button>
    </a>
    <br>
    <a href="{% url 'loginApp:home' %}">
        <button class="btn btn-info font-weight-bold">
            Return to HOME page
        </button>
    </a>
</div>
{% endblock content %}

5lab_django_intro/my_site/loginApp/templates/loginApp/base.html
<!DOCTYPE html>
<html>

<head>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    </head>
<body>
    {% block content %}
    {% endblock %}
</body>

</html>

5lab_django_intro/my_site/loginApp/templates/loginApp/home.html
<head>
    <title>Welcome to afterLOGIN SITE</title>
</head>
{% extends 'loginApp/base.html' %}

{% block content %}

<div class="row m-1 p-1">
    <div class="col">
        <h2>Login Page</h2>
        <a href="{% url 'loginApp:login' %}">Go to Login Page</a>
    </div>
    <div class="col">
        <h2>Admin Page</h2>
        <a href="/admin">Go to Admin Page</a>
    </div>
    <div class="col">
        <h2>Guest User Page</h2>
        <a href="{% url 'obrazkiApp:svg_list' %}">Go to Guest User Page</a>
    </div>
</div>
<br>
<footer class="p-1">
    <p>Have a great day! 😊</p>
</footer>

{% endblock content %}

5lab_django_intro/my_site/loginApp/templates/loginApp/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Welcome to LOGIN SITE</title>
</head>
<body>
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    <p>Thank you for visiting.</p>
    <!-- <a href="/admin/">Go to Admin Site</a> -->
    <br>
    <!-- <a href="{% url 'loginApp:login' %}">Go to Login Page</a> -->
    <a href="{% url 'obrazkiApp:index' %}">Go to obrazkiApp index</a>
    <br>
    <a href="{% url 'loginApp:logout' %}" class="btn btn-outline">Logout</a>
    <br>
</body>
</html>

5lab_django_intro/my_site/loginApp/templates/loginApp/login.html
<head>
    <title>LOGIN SITE</title>
</head>
{% extends 'loginApp/base.html' %}

{% block content %}

<div class="p-1 m-1">

    <p class="font-italic">LOGIN form:</p>
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
        <br>
        <form action="" method="post">
            {% csrf_token %}
            <label for="">username</label>
            <input type="text" name="username" id="">
            <br>
            <label for="">Password</label>
            <input type="password" name="password" id="">
            <br>
            <input type="submit" value="Login">
        </form>
        <br>
        <a href="{% url 'loginApp:home' %}">Home</a>

</div>
{% endblock content %}