5lab_django_intro/my_site/loginApp/urls.py
from django.urls import path
# from .views import MyLoginView
from django.contrib.auth.views import LogoutView 
from . import views

app_name = "loginApp"
urlpatterns = [
    path("", views.home_view, name="home"),
    path('login/', views.loginview, name='login'),
    path("afterLogin/", views.afterLogin, name="afterLogin"),
    path('logout/', views.logout_view ,name='logout'),
]

5lab_django_intro/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from loginApp import views as login_views
urlpatterns = [
    path("", login_views.home_view, name="home"),
    path("obrazkiApp/", include("obrazkiApp.urls")),
    path("loginApp/", include("loginApp.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

5lab_django_intro/my_site/obrazkiApp/urls.py
from django.urls import path
# from .views import MyLoginView
from django.contrib.auth.views import LogoutView 
from . import views

app_name = "obrazkiApp"
urlpatterns = [
    path("", views.index, name="index"),
    path("svg_form/", views.svg_form_view, name="svg_img_form"),
    path("<int:svg_id>/", views.svg_detail, name="svg_detail"),
    path("svg_list/", views.list_svg_images, name="svg_list"),
    path("svg_modifiable_list/", views.svg_modifiable_list, name="svg_modifiable_list"),
    path("<int:svg_id>/modifiable/", views.svg_modifiable_detail, name="svg_modifiable_detail"),
    path("<int:svg_id>/<int:rect_id>/", views.svg_remove_rect, name="svg_remove_rect"),
]

5lab_django_intro/my_site/obrazkiApp/models.py
from typing import Any
from django.db import models
from django.db import models
from django.contrib.auth.models import User
import os
from pathlib import Path
from django.conf import settings
from taggit.managers import TaggableManager

# Create your models here.
class SVG_image(models.Model):
    name = models.CharField(max_length=100, unique=True)
    width = models.PositiveIntegerField()
    height = models.PositiveIntegerField()
    description = models.CharField(max_length=200, blank=True)
    pub_date = models.DateTimeField()
    tags = TaggableManager()
    permitted_users = models.ManyToManyField(User)

    def __str__(self):
        return self.name
    
    def create_svg(self):

        svg_header = f'<svg width="{self.width}" height="{self.height}"  viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">\n'
        svg_end = '</svg>' 
        svg_content = svg_header + svg_end

        file_path = settings.STATIC_ROOT / "svg" / (self.name + ".svg")

        if os.path.exists(file_path):
            file_content = ""
            with open(file_path, 'r') as file:
                # otwieramy plik svg i czytamy cala zawartosc, nastepnie usuwamy
                # naglowek svg i dodajemy nasz nowy naglowek
                file_content = file.read()
                svg_header_end_idx = file_content.find('>')
                file_content = file_content[svg_header_end_idx + 1:]
                file_content = svg_header + file_content
            with open(file_path, 'w') as file:
                file.write(file_content)
        else:
            with open(file_path, 'w') as file:
                file.write(svg_content)

    def save(self, *args, **kwargs):
        self.create_svg()
        # call the parent's save() method
        super(SVG_image, self).save(*args, **kwargs)
    
    def delete(self):
        file_path = settings.STATIC_ROOT / "svg" / (self.name + ".svg")

        if os.path.exists(file_path):
            try:
                os.remove(file_path)
            except Exception as e:
                print(e)

        file_path_thumb = settings.STATIC_ROOT / "svg" / (self.name + "_thumb.svg")
        if os.path.exists(file_path_thumb):
            try:
                os.remove(file_path_thumb)
            except Exception as e:
                print(e)

        super(SVG_image, self).delete()

5lab_django_intro/my_site/obrazkiApp/views.py
from django.shortcuts import render
from django.conf import settings
import os
from .models import SVG_image
from django.contrib.auth.decorators import login_required
import re
import xml.etree.ElementTree as ET
from django.shortcuts import redirect
from django.core.paginator import Paginator
from taggit.models import Tag

ET.register_namespace('',"http://www.w3.org/2000/svg")

# Create your views here.
@login_required
def index(request):
    return render(request, 'obrazkiApp/index.html')

def svg_detail(request, svg_id):
    # trzeba bedzie zmienic na get_object_or_404
    svg_object = SVG_image.objects.get(id=svg_id)

    return render(request, 'obrazkiApp/svg_detail.html', {'svg_object': svg_object})

def make_svg_thumbnails(svg_objects):
    for svg_object in svg_objects:

        main_svg_file_path = settings.STATIC_ROOT / "svg" / (svg_object.name + ".svg")
        resized_file = ""

        if os.path.exists(main_svg_file_path):
            with open(main_svg_file_path, 'r') as file:
                file_content = file.read()
                svg_header_end_idx = file_content.find('>')
                new_header = f'<svg width="{40}" height="{40}"  viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">'
                resized_file = new_header + file_content[svg_header_end_idx + 1:]

        thumbnail_path = settings.STATIC_ROOT / "svg" / (svg_object.name + "_thumb.svg")
        with open(thumbnail_path, "w") as file:
            file.write(resized_file)

def make_svgobject_thumbnail_double_list(svg_objects):
    thumbnails_lst = []
    for svg in svg_objects:
        thumbnails_lst.append(settings.STATIC_ROOT / "svg" / (svg.name + "_thumb"))
    double_lst = list(zip(svg_objects, thumbnails_lst))
    return double_lst

def make_sorted_and_tagged_svg_list(tag_obj, sorted_obj):
    res_lst = []
    for svg in sorted_obj:
        if svg in tag_obj:
            res_lst.append(svg)
    return res_lst

def list_svg_images(request):
    # Sprawdzamy czy dostalismy parametr sort, jesli tak to sprawdzamy czy jest 
    # on rowny 0 lub 1 i sortujemy albo od najstarszej daty do najnowszej 
    # (increasing), albo od najnowszej do najstarszej (decreasing)
    sort = request.GET.get("sort")
    sorted_obj = []
    if (sort):
        if sort != "2":
            if sort == "1":
                sorted_obj = SVG_image.objects.all().order_by('-pub_date')
            else:
                sorted_obj = SVG_image.objects.all().order_by('pub_date')
    
    tag = request.GET.get("tag")
    if (tag):
        svg_objects = SVG_image.objects.filter(tags__name__in=[tag])
    else:
        svg_objects = SVG_image.objects.all()

    if sorted_obj != []:
        svg_objects = make_sorted_and_tagged_svg_list(svg_objects, sorted_obj)

    double_lst = make_svgobject_thumbnail_double_list(svg_objects)
    make_svg_thumbnails(svg_objects)
    pagin = Paginator(double_lst, 4)
    page_number = request.GET.get('page')
    images = pagin.get_page(page_number)
    tags = Tag.objects.all()

    return render(request, 'obrazkiApp/list_svg_images.html', {"images": images, "tags": tags})

@login_required
def svg_form_view(request):
    if request.method == 'POST':
        name = request.POST["name"]
        x = request.POST["x"]
        y = request.POST["y"]
        height = request.POST["height"]
        width = request.POST["width"]
        color = request.POST["color"]

        svg_image = f'<svg height="100" width="100" viewBox="0 0 100 100" ' + 'version="1.1" xmlns="http://www.w3.org/2000/svg">' + f'<rect x="{x}" y="{y}" width="{width}" height="{height}"' + f' fill="{color}"/>' + '</svg>' 

        file_path = os.path.join(settings.MEDIA_ROOT, f'images/{name}.svg')
        with open(file_path, 'w') as file:
            file.write(svg_image)

        return render(request, 'obrazkiApp/svg_img_form.html', {'svg_image_name': name})
    else:
        return render(request, 'obrazkiApp/svg_img_form.html', {})

@login_required
def svg_modifiable_list(request):

    sort = request.GET.get("sort")
    sorted_obj = []
    if (sort):
        if sort != "2":
            if sort == "1":
                sorted_obj = SVG_image.objects.all().order_by('-pub_date')
            else:
                sorted_obj = SVG_image.objects.all().order_by('pub_date')

    tag = request.GET.get("tag")
    if (tag):
        svg_objects = SVG_image.objects.filter(tags__name__in=[tag])
    else:
        svg_objects = SVG_image.objects.all()

    if sorted_obj != []:
        svg_objects = make_sorted_and_tagged_svg_list(svg_objects, sorted_obj)

    modifiable_lst = []

    for svg in svg_objects:
        if svg.permitted_users.filter(id=request.user.id):
            modifiable_lst.append(svg)

    make_svg_thumbnails(modifiable_lst)    
    svgobj_thumb_lst = make_svgobject_thumbnail_double_list(modifiable_lst)

    pagin = Paginator(svgobj_thumb_lst, 4)
    page_number = request.GET.get('page')
    images = pagin.get_page(page_number)

    return render(request, 'obrazkiApp/svg_modifiable_list.html', {'images': images, "tags": Tag.objects.all()})


def add_new_rect(request, file_path):
    x = request.POST["x"]
    y = request.POST["y"]
    height = request.POST["height"]
    width = request.POST["width"]
    color = request.POST["color"]

    if os.path.exists(file_path):
        without_end = ""

        with open(file_path, 'r') as file:
            # otwieramy plik svg i czytamy cala zawartosc, nastepnie    
            # zapamietujemy calosc poza koncem i dodajemy na koniec nowy rect
            file_content = file.read()
            without_end = file_content[:file_content.find('</svg>')]

        new_rect = f'<rect x="{x}" y="{y}" width="{width}" height="{height}" fill="{color}"/>\n'
        new_content = without_end + new_rect + '</svg>'

        with open(file_path, 'w') as file:
            file.write(new_content)

def get_rect_lst(file_path):
    if os.path.exists(file_path):
        file_content = ""
        rect_list = []
        with open(file_path, 'r') as file:
            # otwieramy plik svg i czytamy cala zawartosc, nastepnie    
            # zapamietujemy naglowek svg i oddzielamy obiekty rect 
            file_content = file.read()
            root = ET.fromstring(file_content)
            rect_list = []
            for child in root:
                rect_list.append(child)
        return rect_list

@login_required
def svg_modifiable_detail(request, svg_id):
    svg_object = SVG_image.objects.get(id=svg_id)
    file_path = settings.STATIC_ROOT / "svg" / (svg_object.name + ".svg")

    if request.method == 'POST':
        add_new_rect(request, file_path)

    rect_list = get_rect_lst(file_path)

    return render(request, 'obrazkiApp/svg_modifiable_detail.html', {'svg_object': svg_object, 'rect_list': rect_list})

def remove_rect_helper(file_path, rect_id):
    if os.path.exists(file_path):
        final_file = ""
        with open(file_path, 'r') as file:
            file_content = file.read()
            root = ET.fromstring(file_content)
            rect_list = []

            for child in root:
                rect_list.append(child)

            i = 0
            final_file = file_content[:file_content.find('>') + 1] + "\n"

            for rect in rect_list:
                if i != rect_id:
                    new_rect = f'<rect x="{rect.attrib['x']}" y="{rect.attrib['y']}" width="{rect.attrib['width']}" height="{rect.attrib['height']}" fill="{rect.attrib['fill']}"/>\n'
                    final_file += new_rect
                i += 1 
            final_file += '</svg>'

        with open(file_path, 'w') as file:
            file.write(final_file)

@login_required
def svg_remove_rect(request, svg_id, rect_id):
    svg_object = SVG_image.objects.get(id=svg_id)
    file_path = settings.STATIC_ROOT / "svg" / (svg_object.name + ".svg")

    remove_rect_helper(file_path, rect_id)

    return redirect('obrazkiApp:svg_modifiable_detail', svg_id=svg_id)

5lab_django_intro/my_site/obrazkiApp/templates/obrazkiApp/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Django Tag</title>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    </head>
<body>
    {% block content %}
    {% endblock %}
</body>

</html>

5lab_django_intro/my_site/obrazkiApp/templates/obrazkiApp/index.html
<head>
    <title>Obrazki APp paagee</title>
</head>
{% extends 'obrazkiApp/base.html' %} 

{% block content %}

    <div class="m-1">
    <h1>Welcome to obrazkiAPP webapge </h1>
    <p>This is the homepage with available actions for ArtUser.</p>
    <h2>Here is a sample svg img:</h2>
    <ul>
        <li>
            <svg width="100" height="100" xmlns="http://www.w3.org/2000/svg">
                <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
            </svg>
        </li>
    </ul>
    <p class="font-italic">available actions:</p>
    <a href="{% url 'obrazkiApp:svg_list' %}">Go to SVG list</a>
    <br>
    <a href="{% url 'obrazkiApp:svg_modifiable_list' %}">Go to SVG list with modifiable images</a>
    
    <p>Other:</p>
    <a href="{% url 'loginApp:afterLogin' %}">Return to AfterLogin page</a>
</div>
{% endblock content %}

5lab_django_intro/my_site/obrazkiApp/templates/obrazkiApp/list_svg_images.html
<head>
    <title>List of svg imgs</title>
</head>

{% extends 'obrazkiApp/base.html' %}

{% block content %}
<div class="card-body">
    <div class="container">
        {% if user.is_authenticated %}
        <a class="m-lg-1" href="{% url 'obrazkiApp:index' %}">Return to obrazkiApp main page</a>
        {% else %}
        <a class="m-lg-1" href="{% url 'loginApp:home' %}">Return to main page</a>
        {% endif %}

        <div class="m-1">

            <!-- Sorting by date -->
            <a href="{% url 'obrazkiApp:svg_list' %}?tag={{request.GET.tag}}&sort=1" class="btn btn-light">
                Sort by date newest first
            </a>
            <a href="{% url 'obrazkiApp:svg_list' %}?tag={{request.GET.tag}}&sort=0" class="btn btn-light">
                Sort by date oldest first
            </a>
            <a href="{% url 'obrazkiApp:svg_list' %}?tag={{request.GET.tag}}&sort=2" class="btn btn-light">
                No sort
            </a>

            <!-- Tags - available to choose, chosen -->
            {%if request.GET.tag %}
            <p class="font-italic">Showing articles with tag: <span
                    class=" badge badge-secondary">{{request.GET.tag}}</span>
            </p>
            <a href="{% url 'obrazkiApp:svg_list'%}" class="btn btn-success">
                Remove Tag Filter
            </a>
            {%else %}
            <p>No Tag Filter - showing all images.</span></p>
            {%endif%}

            {% for tag in tags %}
            <a href="{% url 'obrazkiApp:svg_list'%}?tag={{tag}}" class="btn btn-sm btn-outline-secondary">
                {{tag}}
            </a>
            {% endfor %}
        </div>

        <!-- SVG images -->
        <h2 class="m-lg-1">List of available svg images:</h2>

        {% if images %}

        {% for svg_obj, thumbnail in images %}
        <div class="row mb-4 border-top m-lg-1">
            <div class="col">
                <a href="{% url 'obrazkiApp:svg_detail' svg_obj.id %}">
                    <h4>{{ svg_obj.name }}</h4>
                </a>
                <div style="width: 50px; height: 50px;">
                    <a href="{% url 'obrazkiApp:svg_detail' svg_obj.id %}">
                        {% load svg %}
                        <p>{% svg thumbnail %}</p>
                    </a>
                </div>
                <br>
                {%if svg_obj.tags %}
                <h6>tags: </h6>
                <div class="row">
                    <div class="col">
                        {%for svg_tag in svg_obj.tags.all %}
                        <a href="{% url 'obrazkiApp:svg_list'%}?tag={{svg_tag}}"
                            class="btn btn-sm btn-outline-secondary">
                            {{svg_tag}}
                        </a>
                        {%endfor %}
                    </div>
                </div>
                {%endif%}

            </div>
        </div>
        {% endfor %}


        {% else %}
        <p>No svg images are available.</p>
        {% endif %}

        <!-- Pagination -->
        <br>

        {% if images.has_previous %}
        <a href="?page=1&tag={{request.GET.tag}}&sort={{request.GET.sort}}">&laquo; First</a>
        <a href="?page={{images.previous_page_number}}&tag={{request.GET.tag}}&sort={{request.GET.sort}}">Previous</a>
        {% endif %}

        Page {{images.number}} of {{images.paginator.num_pages}}.

        {% if images.has_next %}
        <a href="?page={{images.next_page_number}}&tag={{request.GET.tag}}&sort={{request.GET.sort}}">Next</a>
        <a href="?page={{images.paginator.num_pages}}&tag={{request.GET.tag}}&sort={{request.GET.sort}}">Last &raquo;</a>
        {% endif %}

    </div>
</div>
{% endblock %}

5lab_django_intro/my_site/obrazkiApp/templates/obrazkiApp/svg_detail.html
<head>
    <title>Svg detail</title>
</head>
{% extends 'obrazkiApp/base.html' %} 

{% block content %}
        <div class="m-1">

        <a href="{% url 'obrazkiApp:svg_list' %}">Return to list of SVGs</a>
        <p>NAME: {{svg_object.name}}</p> 
        {% if svg_object.description %}
            <p>DESCRIPTION: {{svg_object.description}}</p>
        {% endif %}
        <p>PUB DATE: {{svg_object.pub_date}}</p>
        <p>TAGS:</p>
        <ul>
        {% for tag in svg_object.tags.all %}
            <li> {{ tag.name }} </li>
        {% endfor %}
        </ul>
        <p>WIDTH x HEIGHT: {{svg_object.width}} x {{svg_object.height}}</p>
        <p>image:</p>
        {% load svg %}
        <h1 class="name">{% svg svg_object.name %}</h1>
        </div>
{% endblock content %}

5lab_django_intro/my_site/obrazkiApp/templates/obrazkiApp/svg_img_form.html
<!DOCTYPE html>
<html>

<body>

    <a href="{% url 'obrazkiApp:index' %}">Return to obrazkiApp index</a>
    <br>
    <br>
    <form action="" method="post">
        {% csrf_token %}
        <label for="name">name:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="x">X:</label>
        <input type="number" id="x" name="x" min="0" required><br>

        <label for="y">Y:</label>
        <input type="number" id="y" name="y" min="0" required><br>

        <label for="width">Width:</label>
        <input type="number" id="width" name="width" min="0" required><br>

        <label for="height">Height:</label>
        <input type="number" id="height" name="height" min="0" required><br>

        <label for="color">Color:</label>
        <input type="color" id="color" name="color" required><br>

        <input type="submit" value="Submit">
    </form>
    <img src="{{ MEDIA_URL }}{{ svg_image_name.svg }}" alt="{{ svg_image_name }}">
</body>

</html>

5lab_django_intro/my_site/obrazkiApp/templates/obrazkiApp/svg_modifiable_detail.html
<head>
    <title>Modifiable svg detail</title>
</head>
{% extends 'obrazkiApp/base.html' %} 

{% block content %}
        <a href="{% url 'obrazkiApp:svg_modifiable_list' %}">Return to list of modifiable SVGs</a>

        {% load svg %}
        <h1 class="name">{% svg svg_object.name %}</h1>

        <h3>DATA:</h3>
        <p>NAME: {{svg_object.name}} <br>
        {% if svg_object.description %}
            <p>DESCRIPTION: {{svg_object.description}}</p>
        {% endif %}
        <p>PUB DATE: {{svg_object.pub_date}}</p>
        <p>TAGS:</p>
        <ul>
        {% for tag in svg_object.tags.all %}
            <li> {{ tag.name }} </li>
        {% endfor %}
        </ul>
        <p>WIDTH x HEIGHT: {{svg_object.width}} x {{svg_object.height}}</p>

        <h3>Prostokąty:</h3>
        <table>
            <tr>
                <th>x</th>
                <th>y</th>
                <th>width</th>
                <th>height</th>
                <th>color</th>
                <th>remove</th>
            </tr>
            {% for rect in rect_list %}
            <tr>
                <td>{{ rect.attrib.x }}</td>
                <td>{{ rect.attrib.y }}</td>
                <td>{{ rect.attrib.width }}</td>
                <td>{{ rect.attrib.height }}</td>
                <td>{{ rect.attrib.fill }}</td>
                <td><a href="{% url 'obrazkiApp:svg_remove_rect' svg_object.id forloop.counter0 %}">remove?</a></td>
            </tr>
            {% endfor %}
        </table>

        <h3>Dodaj nowy prostokąt:</h3>
        <form action="" method="post">
            {% csrf_token %}
            <label for="x">X:</label>
            <input type="number" id="x" name="x" min="0" required><br>

            <label for="y">Y:</label>
            <input type="number" id="y" name="y" min="0" required><br>

            <label for="height">Height:</label>
            <input type="number" id="height" name="height" min="0" required><br>

            <label for="width">Width:</label>
            <input type="number" id="width" name="width" min="0" required><br>

            <label for="color">Color:</label>
            <input type="color" id="color" name="color" required><br>
            <br>
            <input type="submit" value="Submit">
        </form>
{% endblock content %}

5lab_django_intro/my_site/obrazkiApp/templates/obrazkiApp/svg_modifiable_list.html
{% extends 'obrazkiApp/base.html' %} 

{% block content %}
    <div class="card-body">
        <div class="container">
            <a class="m-lg-1" href="{% url 'obrazkiApp:index' %}">Return to obrazkiApp main page</a>

            <div class="m-1">

                <!-- Sorting by date -->
                <a href="{% url 'obrazkiApp:svg_modifiable_list' %}?tag={{request.GET.tag}}&sort=1" class="btn btn-light">
                    Sort by date newest first
                </a>
                <a href="{% url 'obrazkiApp:svg_modifiable_list' %}?tag={{request.GET.tag}}&sort=0" class="btn btn-light">
                    Sort by date oldest first
                </a>
                <a href="{% url 'obrazkiApp:svg_modifiable_list' %}?tag={{request.GET.tag}}&sort=2" class="btn btn-light">
                    No sort
                </a>

                <!-- Tags - available to choose, chosen -->
                {%if request.GET.tag %}
                <p>Showing articles with tag: {{request.GET.tag}}</p>
                <a href="{% url 'obrazkiApp:svg_modifiable_list' %}" class="btn btn-success">
                    Remove Tag Filter
                </a>
                {%else %}
                <p>No Tag Filter - showing all images.</span></p>
                {%endif%}

                {% for tag in tags %}
                <a href="{% url 'obrazkiApp:svg_modifiable_list' %}?tag={{tag}}"
                    class="btn btn-sm btn-outline-secondary">
                    {{tag}}
                </a>
                {% endfor %}
            </div>

            <!-- SVG images -->
            <h2 class="m-lg-1">List of available svg images to modify:</h2>
            {% if images %}
            {% for svg_obj, thumbnail in images %}
            <div class="row mb-4 border-top m-lg-1">
                <div class="col">
                    <a href="{% url 'obrazkiApp:svg_modifiable_detail' svg_obj.id %}">
                        <h4>{{ svg_obj.name }}</h4>
                    </a>
                    <div style="width: 50px; height: 50px;">
                        <a href="{% url 'obrazkiApp:svg_modifiable_detail' svg_obj.id %}">
                            {% load svg %}
                            <p>{% svg thumbnail %}</p>
                        </a>
                    </div>
                    <br>
                    {%if svg_obj.tags %}
                    <h6>tags: </h6>
                    <div class="row">
                        <div class="col">
                            {%for svg_tag in svg_obj.tags.all %}
                            <a href="{% url 'obrazkiApp:svg_modifiable_list'%}?tag={{svg_tag}}"
                                class="btn btn-sm btn-outline-secondary">
                                {{svg_tag}}
                            </a>
                            {%endfor %}
                        </div>
                    </div>
                    {%endif%}

                </div>
            </div>
            {% endfor %}

            {% else %}
            <p>No svg images are available to be modified by You.</p>
            {% endif %}

            <!-- Pagination -->
            <br>

            {% if images.has_previous %}
            <a href="?page=1&tag={{request.GET.tag}}&sort={{request.GET.sort}}">&laquo; First</a>
            <a href="?page={{images.previous_page_number}}&tag={{request.GET.tag}}&sort={{request.GET.sort}}">Previous</a>
            {% endif %}

            Page {{images.number}} of {{images.paginator.num_pages}}.

            {% if images.has_next %}
            <a href="?page={{images.next_page_number}}&tag={{request.GET.tag}}&sort={{request.GET.sort}}">Next</a>
            <a href="?page={{images.paginator.num_pages}}&tag={{request.GET.tag}}&sort={{request.GET.sort}}">Last &raquo;</a>
            {% endif %}
        </div>
    </div>
{% endblock %}